# Generated by Django 4.2.23 on 2025-08-28 12:27

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CardBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Card brand",
                "verbose_name_plural": "Card brands",
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("enabled", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Payment method",
                "verbose_name_plural": "Payment methods",
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="PaymentSimulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cart_id", models.CharField(blank=True, max_length=100, null=True)),
                ("order_id", models.CharField(blank=True, max_length=100, null=True)),
                ("amount_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="ARS", max_length=10)),
                (
                    "change_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="draft", max_length=20)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment simulation",
                "verbose_name_plural": "Payment simulations",
            },
        ),
        migrations.CreateModel(
            name="PaymentSimulationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method_code", models.CharField(max_length=20)),
                ("amount_base", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_credit", models.BooleanField(default=False)),
                ("installments", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "coef_total",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=9, null=True
                    ),
                ),
                (
                    "interest_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("amount_final", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reference", models.CharField(blank=True, max_length=255)),
                ("extra_meta", models.JSONField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "card_brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.cardbrand",
                    ),
                ),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="payments.paymentsimulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment simulation item",
                "verbose_name_plural": "Payment simulation items",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CreditPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installments", models.PositiveIntegerField()),
                ("coef_total", models.DecimalField(decimal_places=4, max_digits=9)),
                (
                    "coef_cuota",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=9, null=True
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.cardbrand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit plan",
                "verbose_name_plural": "Credit plans",
                "unique_together": {("brand", "installments")},
            },
        ),
    ]
