# Generated by Django 4.2.23 on 2025-08-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecuenciaNumerica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("prefijo", models.CharField(blank=True, max_length=20)),
                ("valor_actual", models.PositiveIntegerField(default=0)),
                ("incremento", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Secuencia numérica",
                "verbose_name_plural": "Secuencias numéricas",
            },
        ),
    ]
